
/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.6/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

rootProject.name = "quiz_java"

// Name your app module (you can call it :quiz_java if you want)
include(":quiz_java")
project(":quiz_java").projectDir = file("app")

// Register the library
include(":codedifferently-instructional:instructional-lib")
project(":codedifferently-instructional:instructional-lib").projectDir =
    file("../../lib/java/codedifferently-instructional/instructional-lib")
