/*
This file was generated by the Gradle 'init' task.
*/


plugins {
    java
   id("org.springframework.boot") version "3.1.0"
   id("io.spring.dependency-management") version "1.1.0"
   application
}


java {
   toolchain {
       languageVersion.set(JavaLanguageVersion.of(21))
   }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-text:1.10.0")
    implementation(project(":codedifferently-instructional:instructional-lib"))  // <-- the link to the specific module
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    implementation("org.springframework.boot:spring-boot-starter")
    testImplementation("org.springframework.boot:spring-boot-starter-test")

}



application {
   // Define the main class for the application.
   application { mainClass.set("quiz_java.App") }
tasks.test { useJUnitPlatform() }

}

