/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz_java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appCanInstantiate() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should be instantiable");
    }
    
    @Test void lesson2CanInstantiate() {
        Lesson2 lesson = new Lesson2();
        assertNotNull(lesson, "Lesson2 should be instantiable");
    }
}
