/*
 * This source file was generated by the Gradle 'init' task
 */
package prime_java;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/*
 * Title: IsAPrimeNumberTest.java
 * 
 * Description: This class contains unit tests for the IsAPrimeNumber class.
 * 
 * Created by: Tyran Rice Jr.
 * Date: 2023-10-01
 */
class IsAPrimeNumberTest {

    IsAPrimeNumber primeChecker;

    /*
     * Title: setUp
     * 
     * Description: This method initializes the IsAPrimeNumber instance before each test.
     * 
     * Parameters: None
     * 
     * Returns: None
     */
    @BeforeEach
    public void setUp() {
        primeChecker = new IsAPrimeNumber();
    }

    /*
     * Title: testIsPrime
     * 
     * Description: This method tests the isPrime method for prime numbers.
     */
    @Test
    public void testIsPrime() {
        assertTrue(primeChecker.isPrime(11));
        assertTrue(primeChecker.isPrime(2));
        assertTrue(primeChecker.isPrime(3));
    }

    /*
     * Title: testIsNotPrime
     * 
     * Description: This method tests the isPrime method for non-prime numbers.
     */
    @Test
    public void testIsNotPrime() {
        assertFalse(primeChecker.isPrime(4));
        assertFalse(primeChecker.isPrime(9));
        assertFalse(primeChecker.isPrime(10));
    }

    /*
     * Title: testEdgeCases
     * 
     * Description: This method tests the isPrime method for edge cases.
     */
    @Test 
    public void testEdgeCases() {
        assertFalse(primeChecker.isPrime(1));
        assertFalse(primeChecker.isPrime(0));
        assertFalse(primeChecker.isPrime(-3));
    }
}
