name: Check Lesson 23 Java Pull Request

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "lesson_23/api/java/**"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Lesson 23 with Java
      working-directory: ./lesson_23/api/java
      run: ./gradlew check