
/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz_java;

/**
 * Java port of the assignment app using codedifferently-instructional library
 */
public class App {
    public static void main(String[] args) {
        System.out.println("Starting Quiz Java Application...");
        
        try {
            // Initialize and run the lesson
            Lesson2 lesson = new Lesson2();
            lesson.run();
            
        } catch (Exception e) {
            System.err.println("Error running quiz: " + e.getMessage());
            e.printStackTrace();
        }
    }
}


